source "https://rubygems.org"

# inesita gem
gem 'inesita', '~> 1.0.pre'
gem 'inesita-livereload', '~> 0.1.1'
gem 'inesita-router', '~> 0.4.pre'

# add this gems to minify files on build
#
gem 'uglifier'
gem 'htmlcompressor'

gem 'slim'
gem 'sass'
gem 'rake'
gem 'puma'
