require 'digest'

task default: [:css, :copy, :build]

desc 'copy files'
task 'copy' do
  mkdir_p 'dist/fazic'
  mkdir_p 'dist/itch'
  cp 'fazic.html', 'dist/fazic/index.html'
  cp 'itch.html', 'dist/itch/index.html'
end

desc 'build css'
task :css do
  sh 'sass stylesheet.css.scss > static/stylesheet.css'
end

desc 'build'
task :build do
  sh 'bundle exec inesita build -f'
end
