class Store
  module Commands
    COMMANDS = [
      {name: "ABS", description: "Evaluates to the absolute value (value without the sign) of the given numeric term.", code: %Q{PRINT ABS(-10)\n10}},
      {name: "AND", description: "dzxxcv", code: "assdfsf"},
      {name: "ASC", description: "Evaluates the first char of a string as a numeric index.", code: %Q{PRINT ASC("A")\n65}},
      {name: "ATN", description: "A mathematical function that returns the arc tangent of a numeric value (the inverse function of TAN). The resulting value is the angle in radians of the given tangent.", code: %{PRINT ATN(1)\n0.7854}},
      {name: "CHR", description: "Can be used to convert a number between 0 and 255 into an ASCII-char and is the inverse of the function ASC.", code: %Q{PRINT CHR(49)\n1}},
      {name: "CLR", description: "Deletes all variables.", code: %Q{A=10\nPRINT A\n10\nCLR\nPRINT A\nnull}},
      {name: "COS", description: "Is a mathematical function which evaluates to the cosine for a given angle, a number regarded as being in radians.", code: %Q{PRINT COS(0)\n1.0000}},
      {name: "END", description: "Ends a BASIC-program and the BASIC-Interpreter writes READY. ", code: %Q{10 PRINT "START"\n20 END\n30 PRINT "NEVER HAPPENED"}},
      {name: "EXP", description: "Is a mathemathical function that evaluates the inverse natural LOG of the argument.", code: %Q{PRINT EXP(1)\n2.7183}},
      {name: "FOR", description: "dzxxcv", code: "assdfsf"},
      {name: "GOSUB", description: "Jumps to a subroutine at the indicated line number. The subroutine finalizes using a RETURN command.", code: %Q{10 GOSUB 40\n20 PRINT "HELLO"\n30 END\n40 PRINT "HELLO GOSUB"\n50 RETURN}},
      {name: "GOTO", description: "makes the BASIC interpreter jump to the indicated line and the execution of the BASIC program is continued at that line.", code: %Q{10 PRINT "HELLO"\n20 GOTO 10}},
      {name: "IF", description: "dzxxcv", code: "assdfsf"},
      {name: "INT", description: "dzxxcv", code: "assdfsf"},
      {name: "LEN", description: "dzxxcv", code: "assdfsf"},
      {name: "LET", description: "dzxxcv", code: "assdfsf"},
      {name: "LIST", description: "dzxxcv", code: "assdfsf"},
      {name: "LOAD", description: "dzxxcv", code: "assdfsf"},
      {name: "LOG", description: "dzxxcv", code: "assdfsf"},
      {name: "NEXT", description: "dzxxcv", code: "assdfsf"},
      {name: "NOT", description: "dzxxcv", code: "assdfsf"},
      {name: "OR", description: "dzxxcv", code: "assdfsf"},
      {name: "PRINT", description: "dzxxcv", code: "assdfsf"},
      {name: "REM", description: "dzxxcv", code: "assdfsf"},
      {name: "RETURN", description: "dzxxcv", code: "assdfsf"},
      {name: "RUN", description: "dzxxcv", code: "assdfsf"},
      {name: "SAVE", description: "dzxxcv", code: "assdfsf"},
      {name: "SGN", description: "dzxxcv", code: "assdfsf"},
      {name: "SIN", description: "dzxxcv", code: "assdfsf"},
      {name: "SQR", description: "dzxxcv", code: "assdfsf"},
      {name: "STOP", description: "dzxxcv", code: "assdfsf"},
      {name: "STR", description: "dzxxcv", code: "assdfsf"},
      {name: "TAN", description: "dzxxcv", code: "assdfsf"},
      {name: "VAL", description: "dzxxcv", code: "assdfsf"},
    ]
  end
end
