name: Build GH Page

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build GH Page
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.1'
      - name: Build fazic_site
        run: |
          cd fazic_static
          bundle install
          bundle exec rake
      - name: Setup rust
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Build fazic_wasm_js
        run: |
          cd fazic_wasm_js
          make
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build final sire
        run: |
          cp -r fazic_static/dist .
          cp -r fazic_wasm_js/build dist/test
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'fazic_static/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
