image: rustdocker/rust:stable

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:
  before_script:
    - apt-get update
    - apt-get install libsdl2-2.0-0
  script:
    - cargo test --verbose --jobs 1
  cache:
    paths:
      - target/
      - cargo/<Paste>
