image: rustdocker/rust:stable


variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:
  before_script:
    - env
    - sdl2-config --libs
    - apt-get update -yq
    - apt-get -o dir::cache::archives="apt-cache" install -y libsdl2-2.0-0
  script:
    - cargo test --verbose --jobs 1
  cache:
    paths:
      - apt-cache/
      - target/
      - cargo/
