[package]
name = "fazic"
version = "0.1.0"
authors = ["Michał Kalbarczyk <fazibear@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "~ 0.13"

[dependencies]
lalrpop-util = "~ 0.13"
regex = "~ 0.2"
rand = "~ 0.3"

[dependencies.sdl2]
version = "0.29"
default-features = true
