[package]
name = "fazic"
version = "0.1.0"
authors = ["Michał Kalbarczyk <fazibear@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.12.5"

[dependencies]
lalrpop-util = "0.12.5"
sdl2 = "0.29"
regex = "0.2.1"
