[package]
name = "fazic"
version = "0.1.0"
authors = ["Michał Kalbarczyk <fazibear@gmail.com>"]
build = "build.rs"

[build-dependencies]
peg = { version = "0.5" }

[dependencies]
rand = "~ 0.3"
hyper = "~ 0.10"
hyper-native-tls = "~ 0.2"

[dependencies.sdl2]
version = "0.29"
default-features = true
